version: '3.2'

services:
  fe:
    build: 
      context: ./
    volumes:
      - type: bind
        source: E:/github/incubator-doris/output
        target: /root/output
      - type: bind
        source: ./fe-doris-meta
        target: /root/fe-doris-meta
    restart: always
    environment:
      - FE_ROLE=fe-leader
    command: /root/output/fe/bin/start_fe.sh
    expose:
      - 8030
      - 9020
      - 9030
      - 9010
      - 8000
    ports:
      - 9030:9030
      - 8030:8030
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      doris:
        ipv4_address: 172.19.199.2

  be:
    build: 
      context: ./
    volumes:
      - type: bind
        source: E:/github/incubator-doris/output
        target: /root/output
      - type: bind
        source: ./be-storage
        target: /root/be-storage
    restart: always
    environment:
      - FE_ROLE=be
    command: /root/output/be/bin/start_be.sh
    expose:
      - 9060
      - 8040
      - 9050
      - 8060
    ports:
      - 8040:8040
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      doris:
        ipv4_address: 172.19.199.3


networks:
  doris:
    ipam:
      config:
        - subnet: 172.19.199.0/24


