- id: redeploy-webhook
  execute-command: /webhook/scripts/test.sh
  command-working-directory: /webhook
  response-message: Deployment triggered successfully!
  response-headers:
    - name: X-Example-Header
      value: it works
  success-http-response-code: 200
  incoming-payload-content-type: application/json
  # http-methods: ["POST"]
  include-command-output-in-response: true
  include-command-output-in-response-on-error: true
  pass-arguments-to-command:
    - source: string
      name: arg1
      value: static-value
    - source: payload
      name: arg2
      path: some.json.path
  pass-environment-to-command:
    - source: string
      envname: ENV_VAR
      name: static-env-value
    - source: payload
      name: payloadEnvVar
      path: some.other.path
  pass-file-to-command:
    - source: payload
      envname: PAYLOAD_FILE
      path: file.path
      base64decode: true
  trigger-rule:
    and:
      - match:
          type: value
          value: 421
          parameter:
            source: url
            name: token
  trigger-rule-mismatch-http-response-code: 400
  trigger-signature-soft-failures: true
