version: '3'
services:
  superset:
    image: amancevice/superset
    container_name: mysuperset
    restart: always
    # environment:
      # MAPBOX_API_KEY: ${MAPBOX_API_KEY}
      # SUPERSET_HOME: /etc/superset
    ports:
      - "8088:8088"
    volumes:
      - ./superset_config.py:/usr/local/lib/python3.6/site-packages/superset/superset_config.py
      - ./data:/var/lib/superset