version: '3'
services:
        mail:
                image: bestwu/ewomail
                hostname: mail.longfengpili.xyz
                restart: always
                ports:
                      - "25:25"
                      - "143:143"
                      - "587:587"
                      - "993:993"
                      - "109:109"
                      - "110:110"
                      - "465:465"
                      - "995:995"
                      - "9529:80"
                      - "9530:8080"
                volumes:
                      - ./mysql:/ewomail/mysql/data
                      - ./vmail:/ewomail/mail
                      - ./rainloop:/ewomail/www/rainloop/data
                      - ./ssl/certs/:/etc/ssl/certs/
                      - ./ssl/private/:/etc/ssl/private/
                      - ./ssl/dkim/:/ewomail/dkim/

                environment:
                        - MYSQL_ROOT_PASSWORD=123456789abc
                        - MYSQL_MAIL_PASSWORD=123456789abc
                        
