services:
  alist:
    image: ghcr.io/monlor/xiaoya-alist:latest
    volumes:
      - xiaoya:/data
    ports:
      - "5678:5678"
      - "2345:2345"
      - "2346:2346"
    env_file:
      - env
    restart: unless-stopped
    networks:
      - default

  metadata:
    image: ghcr.io/monlor/xiaoya-metadata:latest
    env_file:
      - env
    volumes:
      - xiaoya:/etc/xiaoya
      - media:/media/xiaoya
      - config:/media/config
      - cache:/media/config/cache
      - jf_media:/media/jf_xiaoya
      - jf_config:/media/jf_config
      - jf_cache:/media/jf_config/cache
      - meta:/media/temp
    depends_on:
      - alist
    restart: unless-stopped
    networks:
      - default

  emby:
    image: ghcr.io/monlor/xiaoya-embyserver:latest
    env_file:
      - env
    depends_on:
      - metadata
      - alist
    volumes:
      - media:/media
      - config:/config
      - cache:/cache
    ports:
      - "6908:6908"
    restart: unless-stopped
    networks:
      - default

  jellyfin:
    image: ghcr.io/monlor/xiaoya-jellyfin:latest
    env_file:
      - env
    privileged: true
    depends_on:
      - metadata
      - alist
    volumes:
      - jf_media:/media
      - jf_config:/config
      - jf_cache:/cache
    ports:
      - 8096:8096
    restart: unless-stopped
    networks:
      - default

networks:
  default:

volumes:
  xiaoya:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./etc/xiaoya
  meta:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volume1/video/xiaoya/meta
  media:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volume1/video/xiaoya/media
  config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volume1/video/xiaoya/config
  cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volume1/video/xiaoya/cache
  jf_media:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volume1/video/xiaoya/jf_media
  jf_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volume1/video/xiaoya/jf_config
  jf_cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volume1/video/xiaoya/jf_cache


