services:
  clash:
    image: dreamacro/clash
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 37890:7890
      - 39090:9090
      - 37891:7891
    volumes:
      - clash-config:/root/.config/clash

  yacd:
    image: haishanh/yacd
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 39080:80

volumes:
  clash-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./config
