services:
  clash:
    image: dreamacro/clash
    restart: always
    environment:
      - TZ=Asia/Shanghai
    expose:
      - 7890
      - 7891
      - 9090
    ports:
      - 27890:7890
      - 27891:7891
      - 29090:9090
    volumes:
      - clash-config:/root/.config/clash

  yacd:
    image: haishanh/yacd
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 29080:80

volumes:
  clash-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./config
