services:
  clash:
    image: dreamacro/clash
    container_name: clash
    restart: always
    environment:
      - TZ=Asia/Shanghai
    expose:
      - 7890
      - 7891
      - 9090
    ports:
      - 6666:7890
      - 27891:7891
      - 29090:9090
    volumes:
      - clash-config:/root/.config/clash
    networks:
      - proxy_net

  yacd:
    image: haishanh/yacd
    container_name: yacd
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 29080:80
    networks:
      - proxy_net

volumes:
  clash-config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./clash

networks:
  proxy_net:
    driver: bridge
