version: "3.8"
services:
  sunpanel:
    image: hslr/sun-panel:latest
    container_name: sunpanel
    privileged: true
    restart: always
    network_mode: bridge
    environment:
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    volumes:
      - /volume1/docker/sunpanel/conf:/app/conf:rw
      - /volume1/docker/sunpanel/uploads:/app/uploads:rw
      - /volume1/docker/sunpanel/database:/app/database:rw
    ports:
      - 23002:3002
