version: "3.8"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    volumes:
      - /volume1/docker/homepage/app:/app
      - /volume1/docker/homepage/config:/config
    ports:
      - 7576:3000
