version: '3'

services:
  jobdb:
    image: mysql
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --innodb-flush-log-at-trx-commit=0 --explicit_defaults_for_timestamp=true
    expose:
      - "3306"
    ports:
      - 8121:3306
    volumes:
      - ./data/mysqldata:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
      - ./mysql/my.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=123456789abc

  cron:
    build: 
      context: ./cron
      dockerfile: Dockerfile
    restart: always
    privileged: true #root权限
    command: 
      - /bin/bash
      - -c
      - |
        env > /etc/default/locale
        cron
        crontab /etc/cron.d/crontab
        tail -f /var/log/cron.log
    volumes:
      - ./code:/workspace
      - ./cron/crontab:/etc/cron.d/crontab

  