version: '3.2'

services:
  nastool:
    image: nastool/nas-tools:3.2.3
    restart: always
    mem_limit: 4G
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    ports:
      - 9090:3000
    volumes:
      - type: bind
        source: ./nastool/nastool/config
        target: /config
      - type: bind
        source: /volume1/video
        target: /video
    network_mode: bridge

  transmission:
    image: linuxserver/transmission:4.0.4
    restart: always
    mem_limit: 4G
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - TRANSMISSION_WEB_HOME=/config/webui
      - USER=longfengpili #optional
      - PASS=xxxxxx #optional
    expose:
      - 9091
    ports:
      - 9091:9091
      - 51413:51413  # Transmission 使用的默认种子端口
      - 51413:51413/udp  # Transmission 使用的默认种子端口（UDP）
    volumes:
      - type: bind
        source: ./nastool/transmission/config
        target: /config
      - type: bind
        source: ./nastool/transmission/watch
        target: /watch
      - type: bind
        source: /volume1/video
        target: /downloads
    network_mode: bridge

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    restart: always
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    ports:
      - 18080:8080
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - type: bind
        source: ./nastool/qbittorrent
        target: /config
      - type: bind
        source: /volume1/video
        target: /downloads
    network_mode: bridge

  jellyfin:
    image: jellyfin/jellyfin:20231009.14-unstable
    restart: always
    mem_limit: 4G
    environment:
      - TZ=Asia/Shanghai
      - HEALTHCHECK_URL=http://longfengpili.cn:9092/health
    expose:
      - 8096
    ports:
      - 9092:8096
    volumes:
      - type: bind
        source: ./nastool/jellyfin/cache
        target: /cache
      - type: bind
        source: ./nastool/jellyfin/config
        target: /config
      - type: bind
        source: /volume1/video
        target: /media
    network_mode: bridge
