version: '3.2'

services:
  nastools:
    image: nastool/nas-tools:3.2.3
    restart: always
    mem_limit: 4G
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    ports:
      - 30000:3000
    volumes:
      - type: bind
        source: /volume1/docker/nastools/config
        target: /config
      - type: bind
        source: /volume1/video
        target: /video
    networks:
      - nasvideo

  transmission:
    image: linuxserver/transmission:4.0.4
    restart: always
    mem_limit: 4G
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - USER=longfengpili #optional
      - PASS=xxxxxx #optional
    ports:
      - 30001:9091
    volumes:
      - type: bind
        source: /volume1/docker/transmission/config
        target: /config
      - type: bind
        source: /volume1/docker/transmission/watch
        target: /watch
      - type: bind
        source: /volume1/video
        target: /downloads
    networks:
      - nasvideo

  jellyfin:
    image: jellyfin/jellyfin:20231009.14-unstable
    restart: always
    mem_limit: 4G
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 30002:8096
    volumes:
      - type: bind
        source: /volume1/docker/jellyfin/cache
        target: /cache
      - type: bind
        source: /volume1/docker/jellyfin/config
        target: /config
      - type: bind
        source: /volume1/video
        target: /media
    networks:
      - nasvideo

networks:
  nasvideo:
    driver: bridge
