version: '3.8'
services:
  grafana:
    image: grafana/grafana-enterprise:10.2.3-ubuntu
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - storage:/var/lib/grafana
      - config:/usr/share/grafana
    environment:
     - GF_INSTALL_PLUGINS=trino-datasource,grafana-clock-panel,fatcloud-windrose-panel,marcusolsson-treemap-panel,isaozler-paretochart-panel,nikosc-percenttrend-panel,netsage-bumpchart-panel
     - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=trino-datasource

volumes:
  storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/storage
  config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/config