services:
  webhook:
    build: 
      context: ./docker
      dockerfile: Dockerfile
    container_name: webhook
    command: -verbose -hooks=/webhook/config/hooks.yaml -hotreload
    ports:
      - "9000:9000"
    # volumes:
    #   - ./config:/webhook/config
    #   - ./scripts:/webhook/scripts

