services:
  nastools:
    image: nastool/nas-tools:latest
    container_name: nastool
    restart: always
    mem_limit: 4G
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    ports:
      - 39090:3000
    volumes:
      - type: bind
        source: ./nastool/config
        target: /config
      - type: bind
        source: /volume1/video
        target: /video
    network_mode: bridge

  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    restart: always
    mem_limit: 4G
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - TRANSMISSION_WEB_HOME=/config/webui
      - USER=xxxx #optional
      - PASS=xxxxx #optional
    expose:
      - 9091
    ports:
      - 39091:9091
      - 51413:51413  # Transmission 使用的默认种子端口
      - 51413:51413/udp  # Transmission 使用的默认种子端口（UDP）
    volumes:
      - type: bind
        source: ./transmission/config
        target: /config
      - type: bind
        source: ./transmission/watch
        target: /watch
      - type: bind
        source: /volume1/video
        target: /downloads
    network_mode: bridge

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    restart: always
    environment:
      - PUID=0
      - PGID=0
      - UMASK_SET=022
      - TZ=Asia/Shanghai
      - WEBUI_PORT=18080
      - TORRENTING_PORT=46881
    ports:
      - 18080:18080
      - 46881:46881
      - 46881:46881/udp
    volumes:
      - type: bind
        source: ./qbittorrent
        target: /config
      - type: bind
        source: /volume1/video
        target: /downloads
    network_mode: bridge

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: always
    mem_limit: 4G
    privileged: true
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      #- HEALTHCHECK_URL=http://127:9092/health
    expose:
      - 8096
    ports:
      - 59092:8096
    volumes:
      - type: bind
        source: ./jellyfin/cache
        target: /cache
      - type: bind
        source: ./jellyfin/config
        target: /config
      - type: bind
        source: /volume1/video
        target: /media
    network_mode: bridge

  stash:
    image: stashapp/stash:latest
    container_name: stash
    restart: always
    network_mode: bridge
    ports:
      - "39999:9999"
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      - STASH_PORT=9999
    volumes:
      - /volume1/video:/data
      - /etc/localtime:/etc/localtime:ro
      - ./stash/config:/root/.stash
      - ./stash/metadata:/metadata
      - ./stash/cache:/cache
      - ./stash/blobs:/blobs
      - ./stash/generated:/generated
