services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: always
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/root/.ollama
    ports:
      - 11434:11434
