services:
  postgresql:
    # environment:
    #   POSTGRES_USER: longfengpili
    #   POSTGRES_PASSWORD: 123456abc
    # healthcheck:
    #   test: psql -U longfengpili -tAc 'select 1' -d openmetadata_db
    #   interval: 15s
    #   timeout: 10s
    #   retries: 10
    volumes:
      - db:/var/lib/postgresql/data

  ingestion:
    volumes:
      - ingestion-python-metadata:/home/airflow/.local/lib/python3.10/site-packages/metadata
      - ingestion-python-pydantic:/home/airflow/.local/lib/python3.10/site-packages/pydantic
      - ingestion-python-gunicorn:/home/airflow/.local/lib/python3.10/site-packages/gunicorn


volumes:
  ingestion-volume-dag-airflow:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/airflow/dag_generated_configs
  ingestion-volume-dags:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/airflow/dags
  ingestion-volume-tmp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/tmp
  es-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/elasticsearch
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/postgresql
  ingestion-python-metadata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/python/metadata
  ingestion-python-gunicorn:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/python/gunicorn
  ingestion-python-pydantic:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/python/pydantic

